#!/usr/bin/env python3
"""
Shared Tao Te Ching quote data for the Taoist Meditation Journal.
30 passages, each with chapter number, English (public domain), and Chinese original.
Used by both generate.py (English) and generate_cn.py (Chinese) to guarantee
page-by-page alignment across language versions.

English translations adapted from James Legge (1891, public domain).
"""

TAO_QUOTES = [
    # (chapter, english, chinese)
    (1,
     "The Tao that can be told is not the eternal Tao. The name that can be named is not the eternal name.",
     "道可道，非常道。名可名，非常名。"),
    (8,
     "The highest good is like water. Water benefits all things and does not contend. It flows in places people reject, and so is like the Tao.",
     "上善若水。水善利万物而不争，处众人之所恶，故几于道。"),
    (11,
     "Thirty spokes share one hub. It is the emptiness inside that makes it useful. Shape clay into a vessel; it is the emptiness inside that makes it useful.",
     "三十辐共一毂，当其无，有车之用。埏埴以为器，当其无，有器之用。"),
    (16,
     "Empty yourself of everything. Let the mind rest at peace. The ten thousand things rise and fall while the Self watches their return.",
     "致虚极，守静笃。万物并作，吾以观复。"),
    (22,
     "Yield and overcome. Bend and be straight. Empty and be full. Wear out and be new. Have little and gain.",
     "曲则全，枉则直，洼则盈，敝则新，少则得，多则惑。"),
    (25,
     "Humans follow the earth. Earth follows heaven. Heaven follows the Tao. The Tao follows what is natural.",
     "人法地，地法天，天法道，道法自然。"),
    (33,
     "Knowing others is intelligence. Knowing yourself is true wisdom. Mastering others is strength. Mastering yourself is true power.",
     "知人者智，自知者明。胜人者有力，自胜者强。"),
    (37,
     "The Tao does nothing, yet nothing is left undone. If leaders could hold to it, all things would transform themselves.",
     "道常无为而无不为。侯王若能守之，万物将自化。"),
    (40,
     "Returning is the motion of the Tao. Yielding is the way of the Tao. All things are born of being. Being is born of non-being.",
     "反者道之动，弱者道之用。天下万物生于有，有生于无。"),
    (43,
     "The softest things in the world overcome the hardest things. That which has no substance enters where there is no space.",
     "天下之至柔，驰骋天下之至坚。无有入无间。"),
    (47,
     "Without going outside your door, you can know the ways of the world. Without peeping through your window, you can see the Tao of heaven.",
     "不出户，知天下。不窥牖，见天道。"),
    (49,
     "The sage has no fixed mind. He takes the mind of the people as his own. He is good to those who are good. He is also good to those who are not good.",
     "圣人常无心，以百姓心为心。善者吾善之，不善者吾亦善之，德善。"),
    (54,
     "Cultivate virtue in yourself, and virtue will be real. Cultivate it in the family, and virtue will abound. Cultivate it in the community, and virtue will multiply.",
     "修之于身，其德乃真。修之于家，其德乃余。修之于乡，其德乃长。"),
    (55,
     "One who is filled with virtue is like a newborn child. Wasps and serpents will not sting, wild beasts will not seize, birds of prey will not strike.",
     "含德之厚，比于赤子。毒虫不螫，猛兽不据，攫鸟不搏。"),
    (56,
     "Those who know do not speak. Those who speak do not know. Close your mouth, block your senses, blunt your sharpness, untie your knots.",
     "知者不言，言者不知。塞其兑，闭其门，挫其锐，解其纷。"),
    (58,
     "When the government is lazy and blunt, the people are kind and honest. When the government is strict and demanding, the people are crafty and restless.",
     "其政闷闷，其民淳淳。其政察察，其民缺缺。祸兮福之所倚，福兮祸之所伏。"),
    (63,
     "Do the difficult while it is easy. Do the great while it is small. The difficult things of the world must be dealt with while they are easy.",
     "图难于其易，为大于其细。天下难事，必作于易。天下大事，必作于细。"),
    (64,
     "A journey of a thousand miles begins beneath your feet. A tree as wide as a person's embrace grows from a tiny shoot.",
     "合抱之木，生于毫末。九层之台，起于累土。千里之行，始于足下。"),
    (66,
     "Rivers and seas can be kings of all valleys because they stay below. Thus the sage wishes to be above people, and speaks from below.",
     "江海所以能为百谷王者，以其善下之，故能为百谷王。"),
    (76,
     "When people are born they are soft and weak. When they die they are stiff and hard. All things, including grass and trees, are soft in life and brittle in death.",
     "人之生也柔弱，其死也坚强。草木之生也柔脆，其死也枯槁。"),
    (78,
     "Nothing in the world is softer than water, yet nothing is better at overcoming the hard and strong. The soft overcomes the hard, the gentle overcomes the strong.",
     "天下莫柔弱于水，而攻坚强者莫之能胜，以其无以易之。弱之胜强，柔之胜刚。"),
    (81,
     "Truthful words are not beautiful. Beautiful words are not truthful. Good people do not argue. Those who argue are not good.",
     "信言不美，美言不信。善者不辩，辩者不善。天之道，利而不害。圣人之道，为而不争。"),
    (9,
     "Fill your bowl to the brim and it will spill. Keep sharpening your knife and it will blunt. Pursue money and security and your heart will never unclench.",
     "持而盈之，不如其已。揣而锐之，不可长保。金玉满堂，莫之能守。"),
    (12,
     "The five colors blind the eye. The five tones deafen the ear. The five flavors dull the taste. Racing and hunting madden the mind.",
     "五色令人目盲，五音令人耳聋，五味令人口爽，驰骋畋猎令人心发狂。"),
    (15,
     "Do you have the patience to wait until your mud settles and the water is clear? Can you remain still until the right action arises by itself?",
     "孰能浊以静之徐清？孰能安以动之徐生？"),
    (19,
     "Throw away holiness and wisdom, and people will be a hundred times happier. Throw away morality and justice, and people will do the right thing.",
     "绝圣弃智，民利百倍。绝仁弃义，民复孝慈。见素抱朴，少私寡欲。"),
    (23,
     "A whirlwind does not last all morning. A sudden rain does not last all day. What is natural does not last long, let alone what is unnatural.",
     "飘风不终朝，骤雨不终日。孰为此者？天地。天地尚不能久，而况于人乎？"),
    (26,
     "The heavy is the root of the light. The still is the master of the restless. Thus the sage travels all day without leaving the baggage behind.",
     "重为轻根，静为躁君。是以君子终日行不离辎重。"),
    (41,
     "The greatest square has no corners. The greatest vessel takes long to complete. The greatest sound is heard note by note. The greatest form has no shape.",
     "大方无隅，大器晚成，大音希声，大象无形。"),
    (45,
     "Great accomplishment seems imperfect, yet its use is never exhausted. Great fullness seems empty, yet its use is endless. Great straightness seems bent.",
     "大成若缺，其用不弊。大盈若冲，其用不穷。大直若屈，大巧若拙。"),
]

if __name__ == "__main__":
    print(f"Total quotes: {len(TAO_QUOTES)}")
    chapters = [q[0] for q in TAO_QUOTES]
    print(f"Chapters: {chapters}")
    print(f"All unique: {len(chapters) == len(set(chapters))}")
